name: Docker Image

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: false
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: ${{ secrets.GITHUB_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ secrets.GITHUB_TOKEN != '' }}
          tags: ghcr.io/${{ github.repository }}:${{ inputs.image_tag }}
          platforms: linux/amd64
